#! /usr/bin/bash
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_038889 > /home/sareh/data/FastTree_outputNC_038889.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001538 > /home/sareh/data/FastTree_outputNC_001538.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_007605 > /home/sareh/data/FastTree_outputNC_007605.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001357 > /home/sareh/data/FastTree_outputNC_001357.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_029645 > /home/sareh/data/FastTree_outputNC_029645.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_044045 > /home/sareh/data/FastTree_outputNC_044045.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_003977 > /home/sareh/data/FastTree_outputNC_003977.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001427 > /home/sareh/data/FastTree_outputNC_001427.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_010956 > /home/sareh/data/FastTree_outputNC_010956.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_039476 > /home/sareh/data/FastTree_outputNC_039476.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_019843 > /home/sareh/data/FastTree_outputNC_019843.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_006273 > /home/sareh/data/FastTree_outputNC_006273.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_004718 > /home/sareh/data/FastTree_outputNC_004718.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001434 > /home/sareh/data/FastTree_outputNC_001434.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001699 > /home/sareh/data/FastTree_outputNC_001699.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_005148 > /home/sareh/data/FastTree_outputNC_005148.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001549 > /home/sareh/data/FastTree_outputNC_001549.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001547 > /home/sareh/data/FastTree_outputNC_001547.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_038294 > /home/sareh/data/FastTree_outputNC_038294.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001355 > /home/sareh/data/FastTree_outputNC_001355.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_009539 > /home/sareh/data/FastTree_outputNC_009539.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_039199 > /home/sareh/data/FastTree_outputNC_039199.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_038270 > /home/sareh/data/FastTree_outputNC_038270.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001796 > /home/sareh/data/FastTree_outputNC_001796.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_003899 > /home/sareh/data/FastTree_outputNC_003899.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_009334 > /home/sareh/data/FastTree_outputNC_009334.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001593 > /home/sareh/data/FastTree_outputNC_001593.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_029646 > /home/sareh/data/FastTree_outputNC_029646.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_044046 > /home/sareh/data/FastTree_outputNC_044046.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_039475 > /home/sareh/data/FastTree_outputNC_039475.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_039223 > /home/sareh/data/FastTree_outputNC_039223.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001414 > /home/sareh/data/FastTree_outputNC_001414.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_044047 > /home/sareh/data/FastTree_outputNC_044047.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_002200 > /home/sareh/data/FastTree_outputNC_002200.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001449 > /home/sareh/data/FastTree_outputNC_001449.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_039897 > /home/sareh/data/FastTree_outputNC_039897.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001498 > /home/sareh/data/FastTree_outputNC_001498.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001802 > /home/sareh/data/FastTree_outputNC_001802.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001436 > /home/sareh/data/FastTree_outputNC_001436.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_006213 > /home/sareh/data/FastTree_outputNC_006213.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_008311 > /home/sareh/data/FastTree_outputNC_008311.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_030454 > /home/sareh/data/FastTree_outputNC_030454.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001542 > /home/sareh/data/FastTree_outputNC_001542.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_003045 > /home/sareh/data/FastTree_outputNC_003045.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_012959 > /home/sareh/data/FastTree_outputNC_012959.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_004455 > /home/sareh/data/FastTree_outputNC_004455.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001348 > /home/sareh/data/FastTree_outputNC_001348.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_000858 > /home/sareh/data/FastTree_outputNC_000858.tre
fasttree -nt -gtr -gamma /home/sareh/data/minimap_alignment/alignment_NC_001526 > /home/sareh/data/FastTree_outputNC_001526.tre
