#! /usr/bin/bash
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_039199.tre 100 > /home/sareh/data/Pruned_FastTree/NC_039199_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_038270.tre 100 > /home/sareh/data/Pruned_FastTree/NC_038270_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001796.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001796_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_039476.tre 100 > /home/sareh/data/Pruned_FastTree/NC_039476_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001538.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001538_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001593.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001593_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_002200.tre 100 > /home/sareh/data/Pruned_FastTree/NC_002200_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_006273.tre 100 > /home/sareh/data/Pruned_FastTree/NC_006273_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_008311.tre 100 > /home/sareh/data/Pruned_FastTree/NC_008311_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_019843.tre 100 > /home/sareh/data/Pruned_FastTree/NC_019843_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001449.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001449_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001526.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001526_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_003045.tre 100 > /home/sareh/data/Pruned_FastTree/NC_003045_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_044045.tre 100 > /home/sareh/data/Pruned_FastTree/NC_044045_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_003899.tre 100 > /home/sareh/data/Pruned_FastTree/NC_003899_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001434.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001434_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_000858.tre 100 > /home/sareh/data/Pruned_FastTree/NC_000858_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_012959.tre 100 > /home/sareh/data/Pruned_FastTree/NC_012959_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_004718.tre 100 > /home/sareh/data/Pruned_FastTree/NC_004718_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_038294.tre 100 > /home/sareh/data/Pruned_FastTree/NC_038294_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_003977.tre 100 > /home/sareh/data/Pruned_FastTree/NC_003977_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_007605.tre 100 > /home/sareh/data/Pruned_FastTree/NC_007605_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001348.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001348_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_006213.tre 100 > /home/sareh/data/Pruned_FastTree/NC_006213_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_038889.tre 100 > /home/sareh/data/Pruned_FastTree/NC_038889_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_029645.tre 100 > /home/sareh/data/Pruned_FastTree/NC_029645_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_039475.tre 100 > /home/sareh/data/Pruned_FastTree/NC_039475_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_044046.tre 100 > /home/sareh/data/Pruned_FastTree/NC_044046_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_029646.tre 100 > /home/sareh/data/Pruned_FastTree/NC_029646_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001547.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001547_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_030454.tre 100 > /home/sareh/data/Pruned_FastTree/NC_030454_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001427.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001427_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_039897.tre 100 > /home/sareh/data/Pruned_FastTree/NC_039897_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001549.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001549_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001498.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001498_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_039223.tre 100 > /home/sareh/data/Pruned_FastTree/NC_039223_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001699.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001699_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_009334.tre 100 > /home/sareh/data/Pruned_FastTree/NC_009334_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001357.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001357_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_009539.tre 100 > /home/sareh/data/Pruned_FastTree/NC_009539_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_005148.tre 100 > /home/sareh/data/Pruned_FastTree/NC_005148_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_004455.tre 100 > /home/sareh/data/Pruned_FastTree/NC_004455_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001542.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001542_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001414.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001414_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_010956.tre 100 > /home/sareh/data/Pruned_FastTree/NC_010956_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001355.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001355_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001802.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001802_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_001436.tre 100 > /home/sareh/data/Pruned_FastTree/NC_001436_pruned.tre
python3 /home/sareh/script/prunetree.py /home/sareh/data/FastTree_output/FastTree_outputNC_044047.tre 100 > /home/sareh/data/Pruned_FastTree/NC_044047_pruned.tre
